# Generated by Django 6.1.1 on 2026-10-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Цена')),
                ('category', models.CharField(choices=[('haircut', 'Haircut'), ('massage', 'Massage'), ('mustache', 'Mustache'), ('beard', 'Beard')], default='haircut', max_length=100, verbose_name='Категория')),
                ('visit_time', models.TimeField(blank=True, null=True, verbose_name='Время визита')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-created_at'],
            },
        ),
    ]
